# DifyRagMnger - config template (日本語)
# 使い方: このファイルをコピーしてプロジェクトルートに config.yml として配置し、
#        CLI 実行時にそのパスを指定してください。
# 注意: API キーは可能なら環境変数で渡すことを推奨します。

# 変換対象フォルダ（絶対パスまたはプロジェクトルートからの相対パス）
input_folder: "./docs"

# Dify Knowledge API の base URL
# 例: https://api.dify.ai/v1
dify_url: "https://api.dify.ai/v1"

# API Key を直接指定する場合（安全上の理由により推奨しません）
# 代替: 環境変数 DIFY_API_KEY を使用する方法を推奨
api_key: "REPLACE_WITH_YOUR_API_KEY"

# デフォルト metadata（任意）
# dataset_id を設定すると、ドキュメント登録は OpenAPI の
# POST /datasets/{dataset_id}/document/create-by-text を使います。
default_metadata:
  dataset_id: null
  source: "local-batch"
  tags: []

# ファイル検出・変換設定
conversion:
  # サポートされる拡張子（大文字/小文字区別なし）
  extensions:
    - ".md"
    - ".txt"
  - ".docx"
  - ".xlsx"
  # Markdown 変換時のエンコーディング
  encoding: "utf-8"
  # markitdown や frontmatter を使う場合のフラグ
  use_markitdown: true
  use_frontmatter: true

# バッチ実行に関する設定
batch:
  # 並列実行ワーカー数（I/O が多い場合は高めに）
  workers: 4
  # Dify API への再試行回数（リトライは指数バックオフ）
  max_retries: 3
  # 一度に送信するドキュメント数（必要に応じて調整）
  batch_size: 10

# ログ設定
logging:
  # ログディレクトリ（相対パス可）
  dir: "./log"
  # ログレベル: DEBUG/INFO/WARNING/ERROR
  level: "INFO"
  # JSON Lines で出力するか
  json_lines: true

# 安全・運用に関するメモ（README に含めるべき事項）
# - API キーはサーバ側で管理し、公開リポジトリや共有ストレージに平文で置かないこと
# - 大きなファイルは事前に分割または create-by-file エンドポイント（multipart/form-data）を使う
# - 本テンプレートは例です。運用環境に合わせて調整してください。

# 例: 環境変数で API キーを渡す場合のサンプル (Windows cmd)
# set DIFY_API_KEY=your_api_key_here

# 例: CLI 実行
# C:\\Work\\workspace\\DifyRagMnger\\.venv\\Scripts\\python.exe -m src.cli.main C:\\Work\\workspace\\DifyRagMnger\\config.yml
